DROP TABLE IF EXISTS PLACE_HISTORIES;
DROP TABLE IF EXISTS PLACE_FILES;
DROP TABLE IF EXISTS PLACES;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  IS_ADMIN BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PLACES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CATEGORY_ID INT,
  LAT DECIMAL(10,7) NOT NULL,
  LNG DECIMAL(10,7) NOT NULL,
  MEMO TEXT,
  IS_PUBLIC BOOLEAN DEFAULT FALSE,
  VALUE INT DEFAULT 0,
  CREATE_USER_ID INT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PLACES_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
  CONSTRAINT FK_PLACES_USER FOREIGN KEY (CREATE_USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE PLACE_FILES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PLACE_ID INT NOT NULL,
  FILE_PATH VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PLACE_FILES_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACES(ID) ON DELETE CASCADE
);

CREATE TABLE PLACE_HISTORIES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PLACE_ID INT NOT NULL,
  VISITED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  COSTS INT DEFAULT 0,
  MEMO TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PLACE_HISTORIES_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACES(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_PLACES_CATEGORY_ID ON PLACES (CATEGORY_ID);